Who can help me?
I've been working in Python recently and I like the programming language very well.

I'd like to create a Python program that shuts down all devices on my network. (IP address space: [192,168,0,0], [192,168,255,255]) We only use Windows 7 and 10 each 64 BIT. - Who has three pupating children knows the reason ... ;-): roll:

I have created the following program, but it does not work. Who can help me or write a better code?

There is the following error message:


ip = raw_input("[[192,168,0,0],[192,168,255,255]]:")
NameError: name 'raw_input' is not defined

Program Design:

import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

ip = raw_input("[[192,168,0,0],[192,168,255,255]]:")
nachricht = raw_input("Nachricht: Jetzt ist Schlafenszeit")

s.sendto(nachricht, (ip, 1))
s.close()

if message == "shutdown" :
ser.close()
os.system("shutdown -h now")
sys.exit()
else: print("Gute Nacht")